# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  repo_root = "../"
  app_name = "GTFONYC"

  desc "Description of what the lane does"
  lane :synx do
    sh "bundle exec synx #{repo_root}#{app_name}.xcodeproj/"
  end
end
